# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

role_admin = Role.create(name: 'admin')
role_external = Role.create(name: 'external')
#User.create(first_name: 'admin', last_name: 'admin', email: 'admin@admin.com', password: 'adminadmin', roles: [role_admin])

Hood.create(name: 'Bosque de Tlalpan')
Hood.create(name: 'Satelite')
Hood.create(name: 'Portales')
Hood.create(name: 'Juarez')
Hood.create(name: 'Iztapalapa')
Hood.create(name: 'Del Valle')
Hood.create(name: 'Coyoacan')
Hood.create(name: 'Tlatelolco')
Hood.create(name: 'Condesa')
Hood.create(name: 'Coapa')
Hood.create(name: 'Churubusco')
Hood.create(name: 'Chapultepec')
#Barrios sin imágenes
Hood.create(name: 'Tepito')
Hood.create(name: 'Roma')
Hood.create(name: 'Juarez')
Hood.create(name: 'Lagunilla')
Hood.create(name: 'Zona Rosa')
Hood.create(name: 'Doctores')
Hood.create(name: 'San Rafael')
Hood.create(name: 'Santa Maria de la Ribera')
Hood.create(name: 'San Miguel Chapultepec')
Hood.create(name: 'Xochimilco')
Hood.create(name: 'Polanco')
Hood.create(name: 'Napoles')
Hood.create(name: 'Narvarte')
Hood.create(name: 'Lindavista')
Hood.create(name: 'Vallejo')
Hood.create(name: 'Central de Abastos')
Hood.create(name: 'La Merced')
Hood.create(name: 'Escandon')
Hood.create(name: 'Peralvillo')
Hood.create(name: 'Agricola Oriental')
Hood.create(name: 'San Angel')
Hood.create(name: 'Santa Fe')
Hood.create(name: 'La Raza')
Hood.create(name: 'San Pedro de los Pinos')
Hood.create(name: 'Rio Blanco')
Hood.create(name: 'Ermita Iztapalapa')
Hood.create(name: 'Tacubaya')
Hood.create(name: 'Virreyes')
Hood.create(name: 'Tlalpan')
Hood.create(name: 'Balbuena')
Hood.create(name: 'Interlomas')
Hood.create(name: 'Barranca Seca')
Hood.create(name: 'San Pedro Mixquic')
#Estados de la república
Hood.create(name: 'Aguascalientes')
Hood.create(name: 'Baja California Norte')
Hood.create(name: 'Baja California Sur')
Hood.create(name: 'Campeche')
Hood.create(name: 'Chiapas')
Hood.create(name: 'Chihuahua')
Hood.create(name: 'Coahuila')
Hood.create(name: 'Colima')
Hood.create(name: 'Durango')
Hood.create(name: 'Estado de Mexico')
Hood.create(name: 'Guanajuato')
Hood.create(name: 'Guerrero')
Hood.create(name: 'Hidalgo')
Hood.create(name: 'Jalisco')
Hood.create(name: 'Hidalgo')
Hood.create(name: 'Michoacan')
Hood.create(name: 'Morelos')
Hood.create(name: 'Nayarit')
Hood.create(name: 'Nuevo Leon')
Hood.create(name: 'Oaxaca')
Hood.create(name: 'Puebla')
Hood.create(name: 'Queretaro')
Hood.create(name: 'Quintana Roo')
Hood.create(name: 'San Luis Potosi')
Hood.create(name: 'Sinaloa')
Hood.create(name: 'Sonora')
Hood.create(name: 'Tabasco')
Hood.create(name: 'Tlaxcala')
Hood.create(name: 'Veracruz')
Hood.create(name: 'Yucatan')
Hood.create(name: 'Zacatecas')
#Ciudades importantes
Hood.create(name: 'Guadalajara')
Hood.create(name: 'Tijuana')
Hood.create(name: 'Leon')
Hood.create(name: 'Monterrey')
Hood.create(name: 'Hermosillo')
Hood.create(name: 'Monterrey')
Hood.create(name: 'Ecatepec')
Hood.create(name: 'Nezahualcoyotl')
#Retos
Challenge.create({:name=> "Social Run", :description=>"Vale mas una carrera entre amigas que un cafe por la tarde. Corran juntas 6km entre 6 y 8 PM.", :start_date => DateTime.new(2014, 2, 11, 6, 0, 1)})
Challenge.create({:name=> "Fast Track", :description=>"Superen los entrenamientos anteriores.", :start_date => DateTime.new(2014, 6, 11, 6, 0, 1)})
Challenge.create({:name=>"Wake Up", :description=>"Despertar temprano es avanzar primero. Elijan un dia y corran las dos antes de las 7 AM.", :start_date => DateTime.new(2014, 3, 10, 6, 0, 1)})
Challenge.create({:name=>"10K", :description=>"Un compromiso entre amigas puede sumar 10 KM en un dia. ¡Demuestrenlo!", :start_date => DateTime.new(2014, 3, 17, 6, 0, 1)})
Challenge.create({:name=>"Marathon", :description=>"Corran en relevos hasta completar un maraton. ¿42 K en un dia? Juntas es mas sencillo.", :start_date => DateTime.new(2014, 2, 11, 6, 0, 1)})
